micronaut:
  application:
    name: micronaut-games
  server:
    port: 8000
r2dbc:
  default:
    url: r2dbc:postgresql://localhost:5432/gamesdb
    username: postgres
    password: mysecretpassword
    db-type: postgres
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      url: jdbc:postgresql://localhost:5432/gamesdb
      username: postgres
      password: mysecretpassword
      driver-class-name: org.postgresql.Driver
      db-type: postgres
      dialect: POSTGRES
jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
endpoints:
  all:
    port: 8001
    path: /
