version: "3.9"

services:
  micronaut-jdbc-native:
    image: ghcr.io/carlomicieli/consolemania-micronaut-jdbc-native:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamesdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - RUN_DB_MIGRATIONS=false
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  micronaut-r2dbc:
    image: ghcr.io/carlomicieli/consolemania-micronaut-r2dbc:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8002:8002
      - 8003:8003
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamesdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - RUN_DB_MIGRATIONS=false
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  spring-mvc-native:
    image: ghcr.io/carlomicieli/consolemania-spring-mvc-native:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8004:8004
      - 8005:8005
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamesdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - RUN_DB_MIGRATIONS=false
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  spring-webflux:
    image: ghcr.io/carlomicieli/consolemania-spring-webflux:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8006:8006
      - 8007:8007
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamesdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
      - RUN_DB_MIGRATIONS=false
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  postgres:
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gamesdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - .docker/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ CMD-SHELL, 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G
    networks:
      - backend

networks:
  backend:
