spring:
  application:
    name: spring-boot-games
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamesdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    enabled: true

server:
  port: 8002
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.data: INFO
    org.springframework.jdbc.core: INFO
    it.consolemania: INFO

management:
  server:
    port: 8003
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
