### Send a new game
POST http://localhost:8000/games
Content-Type: application/json

{
  "title": "Fatal Fury 2",
  "slug": "fatfury2",
  "genres": ["FIGHTING"],
  "platform": "Neo Geo AES",
  "modes": ["SINGLE_PLAYER"],
  "series": "Fatal fury",
  "developer": "SNK",
  "publisher": "SNK",
  "release": {
    "japan": "1990-04-26",
    "north_america": "1990-08-22",
    "europe": "1991-01-01"
  },
  "year": 1994
}

### Send a new game
PUT http://localhost:8000/games/urn:game:neo-geo-aes:fatal-fury-2
Content-Type: application/json

{
  "title": "Fatal Fury 2",
  "slug": "fatfury2",
  "genres": ["FIGHTING"],
  "platform": "Neo Geo AES",
  "modes": ["SINGLE_PLAYER", "MULTIPLAYER"],
  "series": "Fatal fury",
  "developer": "SNK",
  "publisher": "SNK",
  "release": {
    "japan": "1990-04-26",
    "north_america": "1990-08-22",
    "europe": "1991-01-01"
  },
  "year": 1994
}

### Get a game by id
GET http://localhost:8000/games/urn:game:neo-geo-aes:fatal-fury-2
