spring:
  application:
    name: consolemania-spring-webflux
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gamesdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    pool:
      enabled: true
      initial-size: 10
      max-size: 25
  flyway:
    enabled: ${RUN_DB_MIGRATIONS:false}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gamesdb}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}

server:
  port: 8004
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.r2dbc: INFO
    org.springframework.web.reactive: INFO
    it.consolemania: INFO

management:
  server:
    port: 8005
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
