spring:
  application:
    name: consolemania-spring-webflux
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gamesdb
    username: postgres
    password: mysecretpassword
    pool:
      enabled: true
      initial-size: 10
      max-size: 25
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/gamesdb
    user: postgres
    password: mysecretpassword

server:
  port: 8004
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.r2dbc: INFO
    org.springframework.web.reactive: INFO

management:
  server:
    port: 8005
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
