micronaut:
  application:
    name: micronaut-games
  server:
    port: 8000
  serde:
    date-format: yyyy-MM-dd
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${micronaut.db.host:localhost}:${micronaut.db.port:5432}/${micronaut.db.name:gamesdb}
      username: ${micronaut.db.username:postgres}
      password: ${micronaut.db.password:mysecretpassword}
      db-type: postgres
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 48
        maxSize: 48
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: ${micronaut.db.migrations.enabled:true}
      url: jdbc:postgresql://${micronaut.db.host:localhost}:${micronaut.db.port:5432}/${micronaut.db.name:gamesdb}
      username: ${micronaut.db.username:postgres}
      password: ${micronaut.db.password:mysecretpassword}
      driver-class-name: org.postgresql.Driver
      db-type: postgres
      dialect: POSTGRES
endpoints:
  all:
    port: 8001
    path: /
logger:
  levels:
    ROOT: INFO
    it.consolemania: INFO
