micronaut:
  application:
    name: micronaut-games
  server:
    port: 8000
  serde:
    date-format: yyyy-MM-dd
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/gamesdb
      username: postgres
      password: mysecretpassword
      db-type: postgres
      dialect: POSTGRES
      options:
        protocol: postgres
        initialSize: 48
        maxSize: 48
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      url: jdbc:postgresql://localhost:5432/gamesdb
      username: postgres
      password: mysecretpassword
      driver-class-name: org.postgresql.Driver
      db-type: postgres
      dialect: POSTGRES
endpoints:
  all:
    port: 8001
    path: /
logger:
  levels:
    ROOT: INFO
    it.consolemania: INFO
