use serde_derive::{Deserialize, Serialize};
use sqlx::Type;
use strum::{Display, EnumString};

#[derive(Debug, PartialEq, Eq, Clone, Copy, Serialize, Deserialize, Display, EnumString, Type)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[strum(serialize_all = "SCREAMING_SNAKE_CASE")]
#[strum(ascii_case_insensitive)]
#[sqlx(type_name = "VARCHAR")]
#[sqlx(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Genre {
    Action,
    Adventure,
    BallAndPaddle,
    BeatEmUp,
    BoardGames,
    Breakout,
    Cards,
    CardBattle,
    Casino,
    Climbing,
    Compilation,
    Driving,
    Educational,
    Fighter,
    Fighting,
    FirstPersonShooter,
    Flying,
    Gambling,
    GameShow,
    Gun,
    HackAndSlash,
    Mahjong,
    Mature,
    Maze,
    MiniGames,
    Miscellaneous,
    Multimedia,
    MultiPlay,
    Other,
    Party,
    Pinball,
    Platform,
    PoolAndDart,
    Puzzle,
    Quiz,
    Racing,
    RacingDriving,
    RacingMotorbike,
    RacingMotorcycle,
    RunAndGun,
    Rhythm,
    RolePlaying,
    Shooter,
    ShootEmUp,
    Simulation,
    Slots,
    Sports,
    SportsBaseball,
    SportsBasketball,
    SportsBiking,
    SportsBowling,
    SportsBoxing,
    SportsCricket,
    SportsFishing,
    SportsFootball,
    SportsFuturistic,
    SportsGolf,
    SportsHandball,
    SportsHockey,
    SportsHorseRacing,
    SportsHunting,
    SportsOlympic,
    SportsPool,
    SportsPoolAndDart,
    SportsRacing,
    SportsRugby,
    SportsSkateboarding,
    SportsSkating,
    SportsSkiing,
    SportsSnowboarding,
    SportsSoccer,
    SportsSurfing,
    SportsTennis,
    SportsTrackAndField,
    SportsVolleyball,
    SportsWrestling,
    Strategy,
    Tabletop,
    Utility,
    VirtualLife,
    Water,
}
